In [2]:
import numpy as np

def minkowski_addition(A, B):
    # Reshape B to have the same number of dimensions as A
    B_reshaped = np.zeros_like(A)
    B_reshaped[:B.shape[0], :B.shape[1]] = B
    # Perform Minkowski addition of binary images A and B
    # by adding every point in A to every point in B
    return np.unique(np.asarray([(a+b) for a in A for b in B_reshaped]), axis=0)

def minkowski_subtraction(A, B):
    # Reshape B to have the same number of dimensions as A
    B_reshaped = np.zeros_like(A)
    B_reshaped[:B.shape[0], :B.shape[1]] = B
    # Perform Minkowski subtraction of binary images A and B
    # by subtracting every point in B from every point in A
    # and keeping only the resulting points that lie within A
    return np.asarray([a for a in A if np.all([(a+b) in A for b in B_reshaped])])

# Example usage:
A = np.array([[0, 1, 0], [1, 1, 1], [0, 1, 0]])
B = np.array([[1, 1], [1, 1]])
A_plus_B = minkowski_addition(A, B)
A_minus_B = minkowski_subtraction(A, B)
print("A:\n", A)
print("B:\n", B)
print("A ⊕ B:\n", A_plus_B)
print("A ⊖ B:\n", A_minus_B)


A:
 [[0 1 0]
 [1 1 1]
 [0 1 0]]
B:
 [[1 1]
 [1 1]]
A ⊕ B:
 [[0 1 0]
 [1 1 1]
 [1 2 0]
 [2 2 1]]
A ⊖ B:
 [[0 1 0]
 [1 1 1]
 [0 1 0]]
